version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/opt/dev-hiring-challenge
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
      - RAILS_ENV=development
    depends_on:
      - database
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - database
      - redis
    volumes:
      - .:/opt/dev-hiring-challenge
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - RAILS_ENV=development

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'

  webpack_dev_server:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/opt/dev-hiring-challenge
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - RAILS_ENV=development
    depends_on:
      - web

  database:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env/development/database

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"

volumes:
  db_data:
  redis: